// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Cascadia PLM LLC

import type { ItemFieldConfig } from './types'

/**
 * All importable issue fields with their configurations
 */
export const ISSUE_FIELDS: Array<ItemFieldConfig> = [
  {
    field: 'itemNumber',
    label: 'Issue Number',
    required: false,
    autoGenerate: true,
    aliases: [
      'issue number',
      'issue#',
      'issue #',
      'ticket',
      'ticket number',
      'ticket#',
      'item number',
      'number',
      'id',
      'issue id',
      'defect id',
      'defect number',
    ],
    type: 'string',
    example: 'ISS-000001',
  },
  {
    field: 'name',
    label: 'Title',
    required: true,
    aliases: [
      'title',
      'name',
      'summary',
      'subject',
      'issue title',
      'issue name',
      'defect title',
      'problem',
      'headline',
    ],
    type: 'string',
    example: 'Widget fails under load',
  },
  {
    field: 'description',
    label: 'Description',
    required: false,
    aliases: [
      'description',
      'desc',
      'details',
      'notes',
      'comments',
      'body',
      'content',
      'full description',
    ],
    type: 'string',
    example: 'The widget component fails when stress tested at 150% capacity',
  },
  {
    field: 'severity',
    label: 'Severity',
    required: false,
    aliases: ['severity', 'sev', 'impact', 'severity level', 'impact level'],
    type: 'enum',
    enumValues: ['Critical', 'High', 'Medium', 'Low'],
    example: 'High',
  },
  {
    field: 'priority',
    label: 'Priority',
    required: false,
    aliases: ['priority', 'pri', 'urgency', 'priority level', 'importance'],
    type: 'enum',
    enumValues: ['Critical', 'High', 'Medium', 'Low'],
    example: 'High',
  },
  {
    field: 'category',
    label: 'Category',
    required: false,
    aliases: [
      'category',
      'type',
      'issue type',
      'issue category',
      'classification',
      'area',
    ],
    type: 'enum',
    enumValues: [
      'Design',
      'Manufacturing',
      'Quality',
      'Customer',
      'Safety',
      'Other',
    ],
    example: 'Quality',
  },
  {
    field: 'reportedDate',
    label: 'Reported Date',
    required: false,
    aliases: [
      'reported date',
      'date reported',
      'opened',
      'open date',
      'created date',
      'date created',
      'reported on',
      'submitted date',
    ],
    type: 'date',
    example: '2024-01-15',
  },
  {
    field: 'resolution',
    label: 'Resolution',
    required: false,
    aliases: [
      'resolution',
      'fix',
      'solution',
      'fix description',
      'resolved by',
      'action taken',
    ],
    type: 'string',
    example: 'Reinforced mounting brackets',
  },
  {
    field: 'rootCause',
    label: 'Root Cause',
    required: false,
    aliases: [
      'root cause',
      'cause',
      'reason',
      'root cause analysis',
      'rca',
      'why',
    ],
    type: 'string',
    example: 'Insufficient material thickness in bracket design',
  },
]
