// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Cascadia PLM LLC

import type { ItemFieldConfig } from './types'

/**
 * All importable part fields with their configurations
 */
export const PART_FIELDS: Array<ItemFieldConfig> = [
  {
    field: 'itemNumber',
    label: 'Item Number',
    required: false,
    autoGenerate: true,
    aliases: [
      'item number',
      'itemnumber',
      'part number',
      'partnumber',
      'pn',
      'part#',
      'part #',
      'sku',
      'item#',
      'item #',
      'number',
      'id',
    ],
    type: 'string',
    example: 'PN-000001',
  },
  {
    field: 'name',
    label: 'Name',
    required: true,
    aliases: [
      'name',
      'part name',
      'partname',
      'title',
      'description',
      'item name',
      'itemname',
      'component',
      'component name',
    ],
    type: 'string',
    example: 'Aluminum Housing',
  },
  {
    field: 'revision',
    label: 'Revision',
    required: false,
    aliases: ['revision', 'rev', 'version', 'ver', 'release'],
    type: 'string',
    example: '-',
  },
  {
    field: 'description',
    label: 'Description',
    required: false,
    aliases: [
      'description',
      'desc',
      'details',
      'notes',
      'comments',
      'remarks',
      'specification',
      'spec',
    ],
    type: 'string',
    example: 'Main housing for the motor assembly',
  },
  {
    field: 'partType',
    label: 'Type',
    required: false,
    aliases: [
      'part type',
      'parttype',
      'make buy',
      'makebuy',
      'make/buy',
      'make or buy',
      'manufacture',
      'purchase',
      'procurement',
      'source',
      'sourcing',
      'type',
    ],
    type: 'enum',
    enumValues: ['Manufacture', 'Purchase', 'Software', 'Phantom'],
    example: 'Manufacture',
  },
  {
    field: 'material',
    label: 'Material',
    required: false,
    aliases: [
      'material',
      'mat',
      'materials',
      'raw material',
      'substance',
      'composition',
    ],
    type: 'string',
    example: 'Aluminum 6061-T6',
  },
  {
    field: 'weight',
    label: 'Weight',
    required: false,
    aliases: ['weight', 'mass', 'wt'],
    type: 'string',
    example: '2.5',
  },
  {
    field: 'weightUnit',
    label: 'Weight Unit',
    required: false,
    aliases: [
      'weight unit',
      'weightunit',
      'mass unit',
      'wt unit',
      'unit of weight',
      'uom weight',
    ],
    type: 'string',
    example: 'kg',
  },
  {
    field: 'cost',
    label: 'Cost',
    required: false,
    aliases: [
      'cost',
      'price',
      'unit cost',
      'unit price',
      'unitcost',
      'unitprice',
      'amount',
    ],
    type: 'string',
    example: '125.00',
  },
  {
    field: 'costCurrency',
    label: 'Currency',
    required: false,
    aliases: [
      'currency',
      'cost currency',
      'costcurrency',
      'curr',
      'money unit',
    ],
    type: 'string',
    example: 'USD',
  },
  {
    field: 'leadTimeDays',
    label: 'Lead Time (Days)',
    required: false,
    aliases: [
      'lead time',
      'leadtime',
      'lead time days',
      'leadtimedays',
      'lt',
      'lead days',
      'procurement time',
      'delivery time',
    ],
    type: 'number',
    example: '14',
  },
]

/**
 * BOM (Bill of Materials) fields for hierarchical import
 */
export const BOM_FIELDS: Array<ItemFieldConfig> = [
  {
    field: 'level',
    label: 'BOM Level',
    required: false,
    aliases: ['level', 'bom level', 'indent', 'lvl', 'hierarchy'],
    type: 'number',
    example: '0',
  },
  {
    field: 'parentItemNumber',
    label: 'Parent Item Number',
    required: false,
    aliases: [
      'parent',
      'parent item number',
      'parent part number',
      'parent pn',
      'parent p/n',
      'assembly',
      'parent part',
      'parent item',
    ],
    type: 'string',
    example: 'ASM-001',
  },
  {
    field: 'quantity',
    label: 'Quantity',
    required: false,
    aliases: ['qty', 'quantity', 'qty per', 'qty/assy', 'count'],
    type: 'number',
    example: '2',
  },
  {
    field: 'findNumber',
    label: 'Find Number',
    required: false,
    aliases: ['find #', 'find number', 'find no', 'item no', 'seq', 'sequence'],
    type: 'number',
    example: '1',
  },
  {
    field: 'referenceDesignator',
    label: 'Reference Designator',
    required: false,
    aliases: [
      'ref des',
      'reference designator',
      'designator',
      'ref designator',
    ],
    type: 'string',
    example: 'R1, R2',
  },
]
