// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Cascadia PLM LLC

/**
 * Error codes for the Cascadia PLM application.
 * These codes are used to categorize errors and map them to HTTP status codes.
 */
export enum ErrorCode {
  // Authentication (1xxx)
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',

  // Authorization (2xxx)
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ROLE_REQUIRED = 'ROLE_REQUIRED',
  RESOURCE_FORBIDDEN = 'RESOURCE_FORBIDDEN',

  // Validation (3xxx)
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_FIELD_REQUIRED = 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID = 'VALIDATION_FIELD_INVALID',
  VALIDATION_SCHEMA_MISMATCH = 'VALIDATION_SCHEMA_MISMATCH',

  // Resource (4xxx)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',

  // Business Logic (5xxx)
  WORKFLOW_INVALID_TRANSITION = 'WORKFLOW_INVALID_TRANSITION',
  WORKFLOW_ACTION_NOT_ALLOWED = 'WORKFLOW_ACTION_NOT_ALLOWED',
  ITEM_REVISION_CONFLICT = 'ITEM_REVISION_CONFLICT',
  ITEM_RELATIONSHIP_CYCLE = 'ITEM_RELATIONSHIP_CYCLE',
  ITEM_CHECKOUT_REQUIRED = 'ITEM_CHECKOUT_REQUIRED',
  BRANCH_PROTECTED = 'BRANCH_PROTECTED',
  MERGE_CONFLICT = 'MERGE_CONFLICT',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_CHECKOUT_REQUIRED = 'FILE_CHECKOUT_REQUIRED',

  // Database (6xxx)
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED = 'DB_QUERY_FAILED',
  DB_TRANSACTION_FAILED = 'DB_TRANSACTION_FAILED',
  DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION',

  // External Services (7xxx)
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

  // System (8xxx)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  RATE_LIMITED = 'RATE_LIMITED',
  SECRET_DECRYPTION_FAILED = 'SECRET_DECRYPTION_FAILED',
  /**
   * A feature turned off by configuration rather than one that failed. Kept
   * out of the retryable set (errors/retry.ts) deliberately: retrying a
   * feature an administrator switched off can only fail again, which is why
   * the retryable EXTERNAL_SERVICE_UNAVAILABLE is the wrong code for it.
   */
  FEATURE_DISABLED = 'FEATURE_DISABLED',

  // Licensing (10xxx)
  PACKAGE_NOT_LICENSED = 'PACKAGE_NOT_LICENSED',

  // Digital signatures (11xxx)
  SIGNATURE_REQUIRED = 'SIGNATURE_REQUIRED',
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  SIGNATURE_CREDENTIAL_UNAVAILABLE = 'SIGNATURE_CREDENTIAL_UNAVAILABLE',
  SIGNATURE_IDENTITY_MISMATCH = 'SIGNATURE_IDENTITY_MISMATCH',

  // Jobs (9xxx)
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_TYPE_NOT_FOUND = 'JOB_TYPE_NOT_FOUND',
  JOB_ALREADY_COMPLETED = 'JOB_ALREADY_COMPLETED',
  JOB_QUEUE_FAILED = 'JOB_QUEUE_FAILED',
  JOB_HANDLER_NOT_FOUND = 'JOB_HANDLER_NOT_FOUND',
}

/**
 * Maps error codes to HTTP status codes.
 */
export const errorCodeToHttpStatus: Record<ErrorCode, number> = {
  // Auth → 401
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 401,

  // Permission → 403
  [ErrorCode.PERMISSION_DENIED]: 403,
  [ErrorCode.ROLE_REQUIRED]: 403,
  [ErrorCode.RESOURCE_FORBIDDEN]: 403,

  // Validation → 400
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.VALIDATION_FIELD_REQUIRED]: 400,
  [ErrorCode.VALIDATION_FIELD_INVALID]: 400,
  [ErrorCode.VALIDATION_SCHEMA_MISMATCH]: 400,

  // Resource → 404/409/423
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
  [ErrorCode.RESOURCE_CONFLICT]: 409,
  [ErrorCode.RESOURCE_LOCKED]: 423,

  // Business → 403/409/413/415/422
  [ErrorCode.WORKFLOW_INVALID_TRANSITION]: 422,
  [ErrorCode.WORKFLOW_ACTION_NOT_ALLOWED]: 422,
  [ErrorCode.ITEM_REVISION_CONFLICT]: 409,
  [ErrorCode.ITEM_RELATIONSHIP_CYCLE]: 422,
  [ErrorCode.ITEM_CHECKOUT_REQUIRED]: 409,
  [ErrorCode.BRANCH_PROTECTED]: 403,
  [ErrorCode.MERGE_CONFLICT]: 409,
  [ErrorCode.FILE_TOO_LARGE]: 413,
  [ErrorCode.FILE_TYPE_NOT_ALLOWED]: 415,
  [ErrorCode.FILE_CHECKOUT_REQUIRED]: 422,

  // Database → 500/503
  [ErrorCode.DB_CONNECTION_FAILED]: 503,
  [ErrorCode.DB_QUERY_FAILED]: 500,
  [ErrorCode.DB_TRANSACTION_FAILED]: 500,
  [ErrorCode.DB_CONSTRAINT_VIOLATION]: 409,

  // External → 502/503/504
  [ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.EXTERNAL_SERVICE_TIMEOUT]: 504,
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,

  // System → 429/500/501/503
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.NOT_IMPLEMENTED]: 501,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.SECRET_DECRYPTION_FAILED]: 500,
  [ErrorCode.FEATURE_DISABLED]: 503,

  // Licensing → 403
  [ErrorCode.PACKAGE_NOT_LICENSED]: 403,

  // Signatures → 401/403/422
  [ErrorCode.SIGNATURE_REQUIRED]: 422,
  [ErrorCode.SIGNATURE_INVALID]: 401,
  [ErrorCode.SIGNATURE_CREDENTIAL_UNAVAILABLE]: 422,
  [ErrorCode.SIGNATURE_IDENTITY_MISMATCH]: 403,

  // Jobs → 404/409/500/503
  [ErrorCode.JOB_NOT_FOUND]: 404,
  [ErrorCode.JOB_TYPE_NOT_FOUND]: 404,
  [ErrorCode.JOB_ALREADY_COMPLETED]: 409,
  [ErrorCode.JOB_QUEUE_FAILED]: 503,
  [ErrorCode.JOB_HANDLER_NOT_FOUND]: 500,
}
