// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Cascadia PLM LLC

import { and, asc, count, desc, eq, ilike, inArray, or, sql } from 'drizzle-orm'
import { alias } from 'drizzle-orm/pg-core'
import { paginatedOrderBy } from '../db/paginated-order'
import type {
  WorkOrder,
  WorkOrderCreateInput,
  WorkOrderStatus,
  WorkOrderUpdateInput,
} from '@/lib/items/types/work-order'
import { db } from '@/lib/db'
import { likeContains } from '@/lib/db/like-pattern'
import { designs, items, programs, workOrders } from '@/lib/db/schema'
import { NotFoundError } from '@/lib/errors'
import { ItemService } from '@/lib/items/services/ItemService'
import { LifecycleInstanceService } from '@/lib/lifecycles/LifecycleInstanceService'

/**
 * Work orders are items since Phase 2.5 (itemNumber = WO number,
 * items.state = status). This service is a facade over ItemService that
 * preserves the legacy API shape (workOrderNumber, status, createdAt, …)
 * so routes and UI keep working unchanged.
 */

// The part an order builds is a second join against items — alias it.
const partItems = alias(items, 'wo_part_items')

const legacyShape = (row: {
  item: typeof items.$inferSelect
  workOrder: typeof workOrders.$inferSelect
  partItemNumber?: string | null
  partName?: string | null
  partRevision?: string | null
  programName?: string | null
}): WorkOrder => ({
  id: row.item.id,
  workOrderNumber: row.item.itemNumber,
  status: row.item.state,
  partId: row.workOrder.partId,
  quantity: row.workOrder.quantity,
  quantityCompleted: row.workOrder.quantityCompleted,
  priority: row.workOrder.priority as WorkOrder['priority'],
  dueDate: row.workOrder.dueDate,
  customerOrder: row.workOrder.customerOrder,
  notes: row.workOrder.notes,
  assignedTo: row.workOrder.assignedTo ?? [],
  programId: row.workOrder.programId,
  requiresSignOff: row.workOrder.requiresSignOff,
  completedAt: row.workOrder.completedAt,
  createdAt: row.item.createdAt,
  createdBy: row.item.createdBy,
  modifiedAt: row.item.modifiedAt,
  modifiedBy: row.item.modifiedBy,
  part: row.partItemNumber
    ? {
        id: row.workOrder.partId!,
        itemNumber: row.partItemNumber,
        name: row.partName,
        revision: row.partRevision ?? '',
      }
    : null,
  program:
    row.programName && row.workOrder.programId
      ? { id: row.workOrder.programId, name: row.programName }
      : null,
})

export class WorkOrderService {
  /**
   * The program a work order belongs to when the caller named none.
   *
   * A work order is gated on the program it names, and a program-less row now
   * fails closed (`requireWorkOrderAccess`), so the program has to come from
   * somewhere. The part being built already sits in a design and the design
   * already names a program — deriving it here is what keeps the fail-closed
   * rule from hiding ordinary work, because `programId` is optional on the v1
   * body and the create form does not require it.
   *
   * Resolves to `null` for a part in a Library or unassigned design, which
   * legitimately has no program. That row is then an administrator's to
   * repair, which is why the column stays nullable.
   *
   * Public because the routes ask the same question for the opposite reason:
   * when a body names a part *and* a program, they compare this answer against
   * the program given, so the invariant creation establishes by deriving is
   * enforced on the path that supplies one too.
   */
  static async deriveProgramId(partId: string): Promise<string | null> {
    const rows = await db
      .select({ programId: designs.programId })
      .from(items)
      .innerJoin(designs, eq(items.designId, designs.id))
      .where(eq(items.id, partId))
      .limit(1)

    return rows[0]?.programId ?? null
  }

  static async create(
    data: WorkOrderCreateInput,
    userId: string,
  ): Promise<WorkOrder> {
    const programId =
      data.programId ??
      (data.partId ? await this.deriveProgramId(data.partId) : null)

    const created = await ItemService.create(
      'WorkOrder',
      {
        itemType: 'WorkOrder',
        // itemNumber auto-generated by the WO-###### numbering scheme
        name: data.customerOrder ?? undefined,
        state: 'Not Started',
        partId: data.partId,
        quantity: data.quantity,
        priority: data.priority,
        dueDate: data.dueDate,
        customerOrder: data.customerOrder,
        notes: data.notes,
        assignedTo: data.assignedTo,
        programId,
        requiresSignOff: data.requiresSignOff,
      } as never,
      userId,
    )
    const workOrder = await this.findById((created as { id?: string }).id!)
    return workOrder!
  }

  static async findById(id: string): Promise<WorkOrder | null> {
    const results = await db
      .select({
        item: items,
        workOrder: workOrders,
        partItemNumber: partItems.itemNumber,
        partName: partItems.name,
        partRevision: partItems.revision,
        programName: programs.name,
      })
      .from(workOrders)
      .innerJoin(items, eq(workOrders.itemId, items.id))
      .leftJoin(partItems, eq(workOrders.partId, partItems.id))
      .leftJoin(programs, eq(workOrders.programId, programs.id))
      .where(eq(workOrders.itemId, id))

    const row = results[0]
    if (!row) return null
    return legacyShape(row)
  }

  static async update(
    id: string,
    data: WorkOrderUpdateInput,
    userId: string,
  ): Promise<WorkOrder> {
    const existing = await this.findById(id)
    if (!existing) throw new NotFoundError('Work Order', id)

    await ItemService.update(
      id,
      {
        ...(data.customerOrder !== undefined && {
          name: data.customerOrder ?? undefined,
        }),
        ...data,
      },
      userId,
    )

    const updated = await this.findById(id)
    return updated!
  }

  static async delete(id: string, userId: string): Promise<void> {
    const existing = await this.findById(id)
    if (!existing) throw new NotFoundError('Work Order', id)
    await ItemService.delete(id, userId)
  }

  static async search(criteria: {
    status?: string
    partId?: string
    search?: string
    programId?: string
    /**
     * Programs the caller may read, or `null` for unrestricted (cross-program
     * authority). A separate axis from `programId`, which is the program the
     * caller *asked* for — narrowing must never widen.
     */
    accessProgramIds?: Array<string> | null
    limit?: number
    offset?: number
    sortBy?: string
    sortDir?: 'asc' | 'desc'
  }) {
    const conditions = [eq(items.itemType, 'WorkOrder')]

    // A work order names its program directly, so the scope is one condition.
    // A program-less work order is *not* admitted: it is a data gap, not a
    // row that sits outside every boundary, and it fails closed so that this
    // list and the by-id gate answer the same question. `accessProgramIds ===
    // null` is cross-program authority and skips this arm entirely, so an
    // administrator still sees those rows — which is the only way they get
    // repaired.
    if (criteria.accessProgramIds) {
      conditions.push(
        criteria.accessProgramIds.length > 0
          ? inArray(workOrders.programId, criteria.accessProgramIds)
          : sql`false`,
      )
    }

    if (criteria.status) {
      conditions.push(eq(items.state, criteria.status))
    }
    if (criteria.partId) {
      conditions.push(eq(workOrders.partId, criteria.partId))
    }
    if (criteria.programId) {
      conditions.push(eq(workOrders.programId, criteria.programId))
    }
    if (criteria.search) {
      const pattern = likeContains(criteria.search)
      conditions.push(
        or(
          ilike(items.itemNumber, pattern),
          ilike(workOrders.customerOrder, pattern),
        )!,
      )
    }

    const whereClause = and(...conditions)
    const limit = criteria.limit ?? 50
    const offset = criteria.offset ?? 0

    const [results, totalResult] = await Promise.all([
      db
        .select({
          item: items,
          workOrder: workOrders,
          partItemNumber: partItems.itemNumber,
          partName: partItems.name,
          partRevision: partItems.revision,
          programName: programs.name,
        })
        .from(workOrders)
        .innerJoin(items, eq(workOrders.itemId, items.id))
        .leftJoin(partItems, eq(workOrders.partId, partItems.id))
        .leftJoin(programs, eq(workOrders.programId, programs.id))
        .where(whereClause)
        .orderBy(
          ...paginatedOrderBy(
            criteria.sortBy === 'dueDate'
              ? criteria.sortDir === 'asc'
                ? asc(workOrders.dueDate)
                : desc(workOrders.dueDate)
              : criteria.sortBy === 'status'
                ? criteria.sortDir === 'asc'
                  ? asc(items.state)
                  : desc(items.state)
                : desc(items.createdAt),
            items.id,
          ),
        )
        .limit(limit)
        .offset(offset),
      db
        .select({ count: count() })
        .from(workOrders)
        .innerJoin(items, eq(workOrders.itemId, items.id))
        .where(whereClause),
    ])

    return {
      workOrders: results.map(legacyShape),
      total: totalResult[0]?.count ?? 0,
    }
  }

  static async updateStatus(
    id: string,
    newStatus: WorkOrderStatus,
    userId: string,
  ): Promise<WorkOrder> {
    const current = await this.findById(id)
    if (!current) throw new NotFoundError('Work Order', id)

    // Sanctioned Free-lifecycle write path (remediation WI-2.1/2.2): the
    // lifecycle's own transitions decide what moves are legal, so no
    // hand-rolled transition map here.
    //
    // Thin by design. The traveler gate and the completedAt stamp
    // used to live in this method, which left the generic
    // POST /api/v1/items/:id/transition and the transition_item_state AI
    // tool — both of which reach transitionFreeItem directly — able to mark
    // an order Complete over an unfinished traveler, and the row they
    // produced could not be repaired by any route. Both halves now live on
    // the shared path, so this endpoint cannot drift away from it again.
    await LifecycleInstanceService.transitionFreeItem(id, newStatus, userId)

    const updated = await this.findById(id)
    return updated!
  }
}
